/*
	SplineGradeMod.h

	Phase 2: multi-spline list management, porting the ordering/cascading
	behavior validated in splinegrade_mod_prototype.ms (v2) into the C++
	modifier. Each entry (spline node, width, falloff, strength, enabled)
	lives in parallel Tab<> paramblock arrays, applied in list order --
	later entries deform the RESULT of earlier ones (cascading stack
	behavior), same as the prototype.

	ARCHITECTURE: P_AUTO_UI drives the spline list and Add/Remove pick
	buttons via TYPE_NODELISTBOX (Max's own picker -- the same path that
	worked in Phase 1). A hand-rolled PickModeCallback crashed on viewport
	pick in Max 2027. Per-entry width/falloff/strength stay manual because
	auto-UI cannot bind one spinner to "the currently selected tab index":
		- Extra rollup controls (Move Up/Down, selected-entry spinners)
		  are handled in a ParamMap2UserDlgProc.
		- Selecting a listbox entry pushes that entry's Tab values into the
		  spinners; editing a spinner writes back into the Tab at the
		  selected index.

	CONFIDENCE NOTE: the paramblock Tab plumbing and ModifyObject cascade
	loop are a direct, well-understood port of validated logic. The manual
	dialog proc / spinner control wiring is comparatively unfamiliar
	territory for this project -- expect a real build-and-fix cycle here,
	same as Phase 1's paramblock/reference-system debugging, not a
	first-try compile.

	KNOWN LIMITATION carried over unchanged from Phase 1: moving the host
	mesh after applying this modifier does not re-track the spline(s) --
	standard OSMs don't re-trigger ModifyObject on a pure node move. See
	Phase 1 source history for the full writeup. A Space Warp is the
	correct SDK tool for genuinely world-space-reactive behavior; deferred.

	Coordinate-space rule, unchanged from Phase 1: spline geometry pulled
	via EvalWorldState is LOCAL space -- multiply by splineNode->GetNodeTM(t)
	to get world space. Mesh vertices: prefer node->GetNodeTM(t) when node
	is non-null (tracks the object's real position), fall back to mc.tm /
	identity only when node is null (rare background evaluation).
*/

#pragma once

#include "3dsmaxsdk_preinclude.h"
#include "max.h"
#include "iparamm2.h"
#include "iparamb2.h"
#include "shape.h"
#include "simpobj.h"
#include "resource.h"

#define SPLINEGRADEMOD_CLASS_ID Class_ID(0x77166afb, 0x4d7c551d)	// <- unique Class_ID generated by the plugin wizard. Do not change this value.

extern HINSTANCE hInstance;
extern ClassDesc2* GetSplineGradeModDesc();

enum { splinegrademod_params };

enum
{
	pb_splineNodes,		// TYPE_INODE_TAB  -- one entry per spline, in apply order
	pb_widths,			// TYPE_FLOAT_TAB  -- parallel to pb_splineNodes
	pb_falloffs,		// TYPE_FLOAT_TAB  -- parallel
	pb_strengths,		// TYPE_FLOAT_TAB  -- parallel
	pb_enabled,			// TYPE_INT_TAB    -- parallel, 0/1 (TYPE_BOOL_TAB may not exist in this SDK -- verify; INT is a safe fallback)
	pb_samples			// TYPE_INT        -- single global value, NOT per-entry (matches prototype)
};

// Dialog control IDs the companion .rc needs to define (in addition to/
// replacing Phase 1's IDC_ set):
//   IDC_SPLINE_LIST      -- native listbox
//   IDC_ADD_SPLINE       -- button, triggers pick mode
//   IDC_REMOVE_SPLINE    -- button
//   IDC_MOVE_UP          -- button
//   IDC_MOVE_DOWN        -- button
//   IDC_ENTRY_WIDTH_EDIT / IDC_ENTRY_WIDTH_SPIN
//   IDC_ENTRY_FALLOFF_EDIT / IDC_ENTRY_FALLOFF_SPIN
//   IDC_ENTRY_STRENGTH_EDIT / IDC_ENTRY_STRENGTH_SPIN
//   IDC_ENTRY_ENABLED    -- checkbox
//   IDC_SAMPLES_EDIT / IDC_SAMPLES_SPIN  -- global, reused from Phase 1

class SplineGradeMod : public Modifier
{
public:
	IParamBlock2* pblock;
	static IObjParam* ip;

	int selectedIndex;		// currently selected listbox entry, -1 = none
	HWND hPanel;			// dialog HWND, valid only while the rollout is open
	ISpinnerControl* spinWidth;
	ISpinnerControl* spinFalloff;
	ISpinnerControl* spinStrength;

	SplineGradeMod();
	~SplineGradeMod();

	void DeleteThis() override { delete this; }
	Class_ID ClassID() override { return SPLINEGRADEMOD_CLASS_ID; }
	SClass_ID SuperClassID() override { return OSM_CLASS_ID; }
	void GetClassName(MSTR& s, bool localized = true) const override { s = MSTR(_M("RySplineGrade")); }

	int NumParamBlocks() override { return 1; }
	IParamBlock2* GetParamBlock(int i) override { return pblock; }
	IParamBlock2* GetParamBlockByID(BlockID id) override { return (pblock->ID() == id) ? pblock : nullptr; }

	int NumRefs() override { return 1; }
	RefTargetHandle GetReference(int i) override { return pblock; }
	void SetReference(int i, RefTargetHandle rtarg) override { pblock = (IParamBlock2*)rtarg; }
	RefResult NotifyRefChanged(const Interval& changeInt, RefTargetHandle hTarget, PartID& partID, RefMessage message, BOOL propagate = TRUE) override;

	int NumSubs() override { return 1; }
	Animatable* SubAnim(int i) override { return pblock; }
	MSTR SubAnimName(int i, bool localized = true) override { return MSTR(_M("Parameters")); }

	void BeginEditParams(IObjParam* ip, ULONG flags, Animatable* prev) override;
	void EndEditParams(IObjParam* ip, ULONG flags, Animatable* next) override;

	ChannelMask ChannelsUsed() override { return GEOM_CHANNEL | TOPO_CHANNEL; }
	ChannelMask ChannelsChanged() override { return GEOM_CHANNEL; }
	Class_ID InputType() override { return defObjectClassID; }
	void ModifyObject(TimeValue t, ModContext& mc, ObjectState* os, INode* node) override;
	Interval LocalValidity(TimeValue t) override;

	CreateMouseCallBack* GetCreateMouseCallBack() override { return nullptr; }
	const MCHAR* GetObjectName(bool localized) const override { return _M("RySplineGrade"); }

	RefTargetHandle Clone(RemapDir& remap) override;

	// -- UI helpers, called from the dialog proc (see .cpp) --
	void RefreshListbox();
	void LoadSelectedEntryToUI();
	void AddSplineEntry(INode* splineNode);
	void RemoveSelectedEntry();
	void MoveSelectedEntry(int direction);	// -1 = up, +1 = down
	void SyncParallelTabs();				// keep width/falloff/strength/enabled tabs aligned with splineNodes
	int SyncSelectionFromList();			// LB_GETCURSEL → selectedIndex
	void InitEntryControls();				// hook per-entry spinners after ParamMap2 exists

private:
	void SampleSplineToPolyline(INode* splineNode, TimeValue t, int numSamples, Tab<Point3>& outPts, bool& outClosed);
	float ClosestPointOnPolylineXY(const Point3& p, const Tab<Point3>& polyline, bool closed, float& outTargetZ);
	bool PointInPolygonXY(const Point3& p, const Tab<Point3>& polyline);
	bool FitPlaneXY(const Tab<Point3>& pts, float& outA, float& outB, float& outC);
	void DeformWorldPositions(Tab<Point3>& working, const BitArray& vertActive, TimeValue t);
	float FalloffWeight(float lateralDist, float halfWidth, float falloffDist);
};
