//**************************************************************************/
// Copyright (c) 1998-2020 Autodesk, Inc.
// All rights reserved.
// 
// Use of this software is subject to the terms of the Autodesk license 
// agreement provided at the time of installation or download, or which 
// otherwise accompanies this software in either electronic or hard copy form.
//**************************************************************************/
// DESCRIPTION: Plugin Wizard generated plugin
// AUTHOR: 
//***************************************************************************/

#include "FlattenMod.h"

#define FlattenMod_CLASS_ID Class_ID(0x6681f358, 0xdc75bee) // <- this is a unique Class_ID generated by the plugin wizard. Do not change this value.


#define PBLOCK_REF 0


class FlattenMod : public Modifier
{
public:
	// Constructor/Destructor
	FlattenMod();
	virtual ~FlattenMod();

	void DeleteThis() override { delete this; }

	// From Animatable
	const TCHAR* GetObjectName(bool localized) const override { return localized ? GetString(IDS_CLASS_NAME) : _T("FlattenMod"); }

	ChannelMask ChannelsUsed() override { return GEOM_CHANNEL | TOPO_CHANNEL | SELECT_CHANNEL; }
#pragma message(TODO("Add the channels that the modifier actually modifies"))
	ChannelMask ChannelsChanged() override { return GEOM_CHANNEL; }

#pragma message(TODO("Return the ClassID of the object that the modifier can modify"))
	Class_ID InputType() override { return defObjectClassID; }

	void ModifyObject(TimeValue t, ModContext& mc, ObjectState* os, INode* node) override;
	void NotifyInputChanged(const Interval& changeInt, PartID partID, RefMessage message, ModContext* mc) override;

	void NotifyPreCollapse(INode* node, IDerivedObject* derObj, int index) override;
	void NotifyPostCollapse(INode* node, Object* obj, IDerivedObject* derObj, int index) override;

	Interval LocalValidity(TimeValue t) override;

// From BaseObject
#pragma message(TODO("Return true if the modifier changes topology"))
	BOOL ChangeTopology() override { return FALSE; }

	CreateMouseCallBack* GetCreateMouseCallBack() override { return NULL; }

	BOOL HasUVW() override;
	void SetGenUVW(BOOL sw) override;

	void BeginEditParams(IObjParam* ip, ULONG flags, Animatable* prev) override;
	void EndEditParams(IObjParam* ip, ULONG flags, Animatable* next) override;

	virtual Interval GetValidity(TimeValue t);

	// Automatic texture support

	// Loading/Saving
	IOResult Load(ILoad* iload) override;
	IOResult Save(ISave* isave) override;

	// From Animatable
	Class_ID ClassID() override { return FlattenMod_CLASS_ID; }
	SClass_ID SuperClassID() override { return OSM_CLASS_ID; }
	void GetClassName(TSTR& s, bool localized) const override { s = localized ? GetString(IDS_CLASS_NAME) : _T("FlattenMod"); }

	RefTargetHandle Clone(RemapDir& remap) override;
	RefResult NotifyRefChanged(const Interval& changeInt, RefTargetHandle hTarget, PartID& partID, RefMessage message, BOOL propagate) override;

	int NumSubs() override { return 1; }
	TSTR SubAnimName(int /*i*/, bool localized) override { return localized ? GetString(IDS_PARAMS) : _T("Parameters"); }
	Animatable* SubAnim(int /*i*/) override { return pblock; }

	// TODO: Maintain the number or references here
	int NumRefs() override { return 1; }
	RefTargetHandle GetReference(int i) override;

	int NumParamBlocks() override { return 1; } // Return number of ParamBlocks in this instance
	IParamBlock2* GetParamBlock(int /*i*/) override { return pblock; } // Return i'th ParamBlock
	IParamBlock2* GetParamBlockByID(BlockID id) override { return (pblock->ID() == id) ? pblock : NULL; } // Return id'd ParamBlock

protected:
	void SetReference(int, RefTargetHandle rtarg) override;

public:
	// Parameter block
	IParamBlock2* pblock; // Ref 0
};

void FlattenMod::SetReference(int i, RefTargetHandle rtarg)
{
	if (i == PBLOCK_REF)
	{
		pblock = (IParamBlock2*)rtarg;
	}
}

RefTargetHandle FlattenMod::GetReference(int i)
{
	if (i == PBLOCK_REF)
	{
		return pblock;
	}

	return nullptr;
}


class FlattenModClassDesc : public ClassDesc2 
{
public:
	int           IsPublic() override                               { return TRUE; }
	void*         Create(BOOL /*loading = FALSE*/) override         { return new FlattenMod(); }
	const TCHAR*  ClassName() override                              { return GetString(IDS_CLASS_NAME); }
	const TCHAR*  NonLocalizedClassName() override                  { return _T("FlattenMod"); }
	SClass_ID     SuperClassID() override                           { return OSM_CLASS_ID; }
	Class_ID      ClassID() override                                { return FlattenMod_CLASS_ID; }
	const TCHAR*  Category() override                               { return GetString(IDS_CATEGORY); }

	const TCHAR*  InternalName() override                           { return _T("FlattenMod"); } // Returns fixed parsable name (scripter-visible name)
	HINSTANCE     HInstance() override                              { return hInstance; } // Returns owning module handle


};

ClassDesc2* GetFlattenModDesc()
{
	static FlattenModClassDesc FlattenModDesc;
	return &FlattenModDesc; 
}

class FlattenModDlgProc : public ParamMap2UserDlgProc
{
public:
	FlattenMod* mod;

	FlattenModDlgProc(FlattenMod* m) : mod(m) {}

	INT_PTR DlgProc(TimeValue t, IParamMap2* map, HWND hWnd,
		UINT msg, WPARAM wParam, LPARAM lParam) override
	{
		switch (msg)
		{
		case WM_INITDIALOG:
			UpdateAxisButtons(hWnd);
			UpdateModeButtons(hWnd);
			break;

		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
			case IDC_RADIO_X:
				mod->pblock->SetValue(pb_axis, t, 0);
				break;
			case IDC_RADIO_Y:
				mod->pblock->SetValue(pb_axis, t, 1);
				break;
			case IDC_RADIO_Z:
				mod->pblock->SetValue(pb_axis, t, 2);
				break;
			case IDC_RADIO_TOVALUE:
				mod->pblock->SetValue(pb_flatten_mode, t, 0);
				break;
			case IDC_RADIO_TOAVERAGE:
				mod->pblock->SetValue(pb_flatten_mode, t, 1);
				break;
			}
			break;
		}
		return FALSE;
	}

	void UpdateAxisButtons(HWND hWnd)
	{
		int axis = 0;
		mod->pblock->GetValue(pb_axis, 0, axis, FOREVER);
		CheckDlgButton(hWnd, IDC_RADIO_X, axis == 0);
		CheckDlgButton(hWnd, IDC_RADIO_Y, axis == 1);
		CheckDlgButton(hWnd, IDC_RADIO_Z, axis == 2);
	}

	void UpdateModeButtons(HWND hWnd)
	{
		int mode = 0;
		mod->pblock->GetValue(pb_flatten_mode, 0, mode, FOREVER);
		CheckDlgButton(hWnd, IDC_RADIO_TOVALUE, mode == 0);
		CheckDlgButton(hWnd, IDC_RADIO_TOAVERAGE, mode == 1);
	}

	void DeleteThis() override { delete this; }
};




static ParamBlockDesc2 flattenmod_param_blk(
	flattenmod_params, _T("params"), 0, GetFlattenModDesc(),
	P_AUTO_CONSTRUCT + P_AUTO_UI, PBLOCK_REF,
	// rollout
	IDD_PANEL, IDS_PARAMS, 0, 0, NULL,

	// axis
	pb_axis, _T("axis"), TYPE_INT, 0, IDS_AXIS,
	p_default, 2,  // default Z
	p_range, 0, 2,
	p_end,

	// flatten mode
	pb_flatten_mode, _T("flatten_mode"), TYPE_INT, 0, IDS_FLATTEN_MODE,
	p_default, 0,  // default ToValue
	p_range, 0, 1,
	p_end,

	// flatten value
	pb_flatten_value, _T("flatten_value"), TYPE_FLOAT, P_ANIMATABLE, IDS_FLATTEN_VALUE,
	p_default, 0.0f,
	p_range, -1000000.0f, 1000000.0f,
	p_ui, TYPE_SPINNER, EDITTYPE_UNIVERSE, IDC_EDIT_VALUE, IDC_SPIN_VALUE, 0.1f,
	p_end,

	// weight
	pb_weight, _T("weight"), TYPE_FLOAT, P_ANIMATABLE, IDS_WEIGHT,
	p_default, 1.0f,
	p_range, 0.0f, 1.0f,
	p_ui, TYPE_SPINNER, EDITTYPE_FLOAT, IDC_EDIT_WEIGHT, IDC_SPIN_WEIGHT, 0.01f,
	p_end,

	p_end
);



//--- FlattenMod -------------------------------------------------------
FlattenMod::FlattenMod()
	: pblock(nullptr)
{
	GetFlattenModDesc()->MakeAutoParamBlocks(this);
}

FlattenMod::~FlattenMod()
{

}

/*===========================================================================*\
 |  The validity of the parameters. First a test for editing is performed
 |  then Start at FOREVER, and intersect with the validity of each item
\*===========================================================================*/
Interval FlattenMod::LocalValidity(TimeValue /*t*/)
{

	return FOREVER;
}

/*************************************************************************************************
*
	Between NotifyPreCollapse and NotifyPostCollapse, Modify is
	called by the system. NotifyPreCollapse can be used to save any plugin dependant data e.g.
	LocalModData
*
\*************************************************************************************************/

void FlattenMod::NotifyPreCollapse(INode* /*node*/, IDerivedObject* /*derObj*/, int /*index*/)
{
#pragma message(TODO("Perform any Pre Stack Collapse methods here"))
}

/*************************************************************************************************
*
	NotifyPostCollapse can be used to apply the modifier back onto to the stack, copying over the
	stored data from the temporary storage. To reapply the modifier the following code can be
	used

	Object* bo = node->GetObjectRef();
	IDerivedObject* derob = NULL;
	if(bo->SuperClassID() != GEN_DERIVOB_CLASS_ID)
	{
		derob = CreateDerivedObject(obj);
		node->SetObjectRef(derob);
	}
	else
	{
		derob = (IDerivedObject*) bo;
	}

	// Add ourselves to the top of the stack
	derob->AddModifier(this,NULL,derob->NumModifiers());

*
\*************************************************************************************************/

void FlattenMod::NotifyPostCollapse(INode* /*node*/, Object* /*obj*/, IDerivedObject* /*derObj*/, int /*index*/)
{
#pragma message(TODO("Perform any Post Stack collapse methods here."))
}


// Builds a BitArray of verts to affect based on current selection level
// For vert sel: direct. For edge/face sel: collect verts from selected edges/faces.
void GetVertInfluences_MN(MNMesh& mesh, float weight, Tab<float>& influences)
{
	influences.SetCount(mesh.numv);
	for (int i = 0; i < mesh.numv; i++)
		influences[i] = 0.0f;

	float* softSel = mesh.getVSelectionWeights();

	if (softSel)
	{
		// soft selection active — use weights directly regardless of sel level
		for (int i = 0; i < mesh.numv; i++)
		{
			if (mesh.v[i].GetFlag(MN_DEAD)) continue;
			influences[i] = softSel[i] * weight;
		}
		return;
	}

	// no soft selection — build binary influences from selection level
	bool anySelection = false;

	switch (mesh.selLevel)
	{
	case MNM_SL_VERTEX:
		for (int i = 0; i < mesh.numv; i++)
		{
			if (mesh.v[i].GetFlag(MN_DEAD)) continue;
			if (mesh.v[i].GetFlag(MN_SEL))
			{
				influences[i] = weight;
				anySelection = true;
			}
		}
		break;

	case MNM_SL_EDGE:
		for (int i = 0; i < mesh.nume; i++)
		{
			if (mesh.e[i].GetFlag(MN_DEAD)) continue;
			if (mesh.e[i].GetFlag(MN_SEL))
			{
				influences[mesh.e[i].v1] = weight;
				influences[mesh.e[i].v2] = weight;
				anySelection = true;
			}
		}
		break;

	case MNM_SL_FACE:
		for (int i = 0; i < mesh.numf; i++)
		{
			if (mesh.f[i].GetFlag(MN_DEAD)) continue;
			if (mesh.f[i].GetFlag(MN_SEL))
			{
				for (int j = 0; j < mesh.f[i].deg; j++)
				{
					influences[mesh.f[i].vtx[j]] = weight;
					anySelection = true;
				}
			}
		}
		break;

	default:
		break;
	}

	// no selection at all — affect everything
	if (!anySelection)
	{
		for (int i = 0; i < mesh.numv; i++)
		{
			if (mesh.v[i].GetFlag(MN_DEAD)) continue;
			influences[i] = weight;
		}
	}
}

void GetVertInfluences_Tri(Mesh& mesh, float weight, Tab<float>& influences)
{
	influences.SetCount(mesh.numVerts);
	for (int i = 0; i < mesh.numVerts; i++)
		influences[i] = 0.0f;

	float* softSel = mesh.getVSelectionWeights();

	if (softSel)
	{
		for (int i = 0; i < mesh.numVerts; i++)
			influences[i] = softSel[i] * weight;
		return;
	}

	bool anySelection = false;

	switch (mesh.selLevel)
	{
	case MESH_VERTEX:
	{
		BitArray& sel = mesh.VertSel();
		for (int i = 0; i < mesh.numVerts; i++)
		{
			if (sel[i])
			{
				influences[i] = weight;
				anySelection = true;
			}
		}
		break;
	}

	case MESH_EDGE:
		for (int i = 0; i < mesh.numFaces; i++)
		{
			for (int j = 0; j < 3; j++)
			{
				if (mesh.EdgeSel()[i * 3 + j])
				{
					influences[mesh.faces[i].v[j]] = weight;
					influences[mesh.faces[i].v[(j + 1) % 3]] = weight;
					anySelection = true;
				}
			}
		}
		break;

	case MESH_FACE:
	{
		BitArray& sel = mesh.FaceSel();
		for (int i = 0; i < mesh.numFaces; i++)
		{
			if (sel[i])
			{
				influences[mesh.faces[i].v[0]] = weight;
				influences[mesh.faces[i].v[1]] = weight;
				influences[mesh.faces[i].v[2]] = weight;
				anySelection = true;
			}
		}
		break;
	}

	default:
		break;
	}

	if (!anySelection)
	{
		for (int i = 0; i < mesh.numVerts; i++)
			influences[i] = weight;
	}
}/*************************************************************************************************
*
	ModifyObject will do all the work in a full modifier
	This includes casting objects to their correct form, doing modifications
	changing their parameters, etc
*
\************************************************************************************************/
void FlattenMod::ModifyObject(TimeValue t, ModContext& mc, ObjectState* os, INode* node)
{
	// Read params
	int   axis = 2;     // default Z
	int   mode = 0;     // default ToValue
	float flattenValue = 0.0f;
	float weight = 1.0f;

	pblock->GetValue(pb_axis, t, axis, FOREVER);
	pblock->GetValue(pb_flatten_mode, t, mode, FOREVER);
	pblock->GetValue(pb_flatten_value, t, flattenValue, FOREVER);
	pblock->GetValue(pb_weight, t, weight, FOREVER);

	// ---- PolyObject path ----
	if (os->obj->IsSubClassOf(polyObjectClassID))
	{
		PolyObject* poly = static_cast<PolyObject*>(os->obj);
		MNMesh& mesh = poly->GetMesh();

		Tab<float> influences;
		GetVertInfluences_MN(mesh, weight, influences);

		// compute average if needed
		if (mode == 1)
		{
			double sum = 0.0;
			int count = 0;
			for (int i = 0; i < mesh.numv; i++)
			{
				if (mesh.v[i].GetFlag(MN_DEAD)) continue;
				if (influences[i] == 0.0f) continue;
				sum += mesh.v[i].p[axis];
				count++;
			}
			if (count > 0)
				flattenValue = (float)(sum / count);
		}

		for (int i = 0; i < mesh.numv; i++)
		{
			if (mesh.v[i].GetFlag(MN_DEAD)) continue;
			if (influences[i] == 0.0f) continue;
			float orig = mesh.v[i].p[axis];
			mesh.v[i].p[axis] = orig + (flattenValue - orig) * influences[i];
		}

		mesh.InvalidateGeomCache();
		return;
	}

	// ---- TriObject path ----
	if (os->obj->IsSubClassOf(triObjectClassID))
	{
		TriObject* tri = static_cast<TriObject*>(os->obj);
		Mesh& mesh = tri->GetMesh();

		Tab<float> influences;
		GetVertInfluences_Tri(mesh, weight, influences);

		// compute average if needed
		if (mode == 1)
		{
			double sum = 0.0;
			int count = 0;
			for (int i = 0; i < mesh.numVerts; i++)
			{
				if (influences[i] == 0.0f) continue;
				sum += mesh.verts[i][axis];
				count++;
			}
			if (count > 0)
				flattenValue = (float)(sum / count);
		}

		for (int i = 0; i < mesh.numVerts; i++)
		{
			if (influences[i] == 0.0f) continue;
			float orig = mesh.verts[i][axis];
			mesh.verts[i][axis] = orig + (flattenValue - orig) * influences[i];
		}

		mesh.InvalidateGeomCache();
		return;
	}

}

void FlattenMod::BeginEditParams(IObjParam* ip, ULONG flags, Animatable* prev)
{
	TimeValue t = ip->GetTime();
	NotifyDependents(Interval(t, t), PART_ALL, REFMSG_BEGIN_EDIT);
	NotifyDependents(Interval(t, t), PART_ALL, REFMSG_MOD_DISPLAY_ON);
	SetAFlag(A_MOD_BEING_EDITED);

	GetFlattenModDesc()->BeginEditParams(ip, this, flags, prev);

	// Register the DlgProc for radio button handling
	flattenmod_param_blk.SetUserDlgProc(new FlattenModDlgProc(this));
}

void FlattenMod::EndEditParams(IObjParam* ip, ULONG flags, Animatable* next)
{
	GetFlattenModDesc()->EndEditParams(ip, this, flags, next);

	TimeValue t = ip->GetTime();
	ClearAFlag(A_MOD_BEING_EDITED);
	NotifyDependents(Interval(t, t), PART_ALL, REFMSG_END_EDIT);
	NotifyDependents(Interval(t, t), PART_ALL, REFMSG_MOD_DISPLAY_OFF);
}

Interval FlattenMod::GetValidity(TimeValue /*t*/)
{
	Interval valid = FOREVER;
#pragma message(TODO("Return the validity interval of the modifier"))
	return valid;
}

RefTargetHandle FlattenMod::Clone(RemapDir& remap)
{
	FlattenMod* newmod = new FlattenMod();
#pragma message(TODO("Add the cloning code here"))
	newmod->ReplaceReference(PBLOCK_REF, remap.CloneRef(pblock));
	BaseClone(this, newmod, remap);
	return (newmod);
}

// From ReferenceMaker
RefResult FlattenMod::NotifyRefChanged(const Interval& /*changeInt*/, RefTargetHandle hTarget, PartID& /*partID*/, RefMessage message, BOOL /*propagate*/)
{
#pragma message(TODO("Add code to handle the various reference changed messages"))
	switch (message)
	{
	case REFMSG_TARGET_DELETED:
	{
		if (hTarget == pblock)
		{
			pblock = nullptr;
		}
	}
	break;
	}
	return REF_SUCCEED;
}

/****************************************************************************************
*
	NotifyInputChanged is called each time the input object is changed in some way
	We can find out how it was changed by checking partID and message
*
\****************************************************************************************/

void FlattenMod::NotifyInputChanged(const Interval& /*changeInt*/, PartID /*partID*/, RefMessage /*message*/, ModContext* /*mc*/)
{

}

// From Object
BOOL FlattenMod::HasUVW()
{
#pragma message(TODO("Return whether the object has UVW coordinates or not"))
	return TRUE;
}

void FlattenMod::SetGenUVW(BOOL sw)
{
	if (sw == HasUVW())
	{
		return;
	}

#pragma message(TODO("Set the plugin internal value to sw"))
}

IOResult FlattenMod::Load(ILoad* iload)
{
	Modifier::Load(iload);

#pragma message(TODO("Add code to allow plugin to load its data"))

	return IO_OK;
}

IOResult FlattenMod::Save(ISave* isave)
{
	Modifier::Save(isave);

#pragma message(TODO("Add code to allow plugin to save its data"))

	return IO_OK;
}
